# This is a basic workflow to help you get started with Actions
name: Yandex.Cloud CI/CD pipeline

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the main branch
  pull_request:
    branches:
    - main
  push:
    branches:
      - feature/gh-actions
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:


jobs:
  upload-serveless-function:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master
      - name: Deploy Function
        uses: goodsmileduck/yandex-serverless-action@v1
        with:
          token: ${{ secrets.YC_TOKEN }}
          function_id: ${{ secrets.YC_FUNCTION_ID }}
          runtime: 'golang117'
          entrypoint: 'main.Handler'
          memory: '256Mb'
          environment: ENVIRONMENT=development,SPACE_HOST=https://space.cloud.mts.ru,SPACE_DEBUG_CHANNEL=4anH4q38FKzj,SPACE_TOKEN=${{ secrets.SPACE_TOKEN }}
          exclude: '.git/**,.github/**,.gitignore'