# This is a basic workflow to help you get started with Actions
name: Yandex.Cloud CI/CD pipeline

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the main branch
  pull_request:
    branches: [ main ]
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:


jobs:
  upload-serveless-function:
    runs-on: ubuntu-latest
    steps:
      - name: Deploy Function
        id: sls-func
        uses: yc-actions/yc-sls-function@v2
        with:
          yc-sa-json-credentials: ${{ secrets.YC_SA_JSON_CREDENTIALS }}
          folder-id: 'b1gralifrlhh1ata3enc'
          function-name: 'pingo'
          entrypoint: 'main.Handler'
          environment: |
            ENVIRONMENT=development
            SPACE_HOST=https://space.cloud.mts.ru
            SPACE_DEBUG_CHANNEL=4anH4q38FKzj
            SPACE_TOKEN=${{ secrets.SPACE_TOKEN }}
          tags: ${{ GITHUB_SHA::6 }}
          include: |
            **/*.go
            go.mod
            go.sum
          exclude: ""
          runtime: 'golang117'
          memory: '256Mb'



